# Generated by Django 5.2.7 on 2025-11-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangleepage', '0002_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
                ('gia', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(upload_to='sanpham/')),
                ('noi_bat', models.BooleanField(default=False)),
            ],
        ),
    ]
