# Generated by Django 5.2.7 on 2025-11-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangleepage', '0003_sanpham'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide/')),
                ('mo_ta', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
