# Generated by Django 5.2.7 on 2025-11-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangleepage', '0004_slideimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrangNoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_trang', models.CharField(max_length=100, unique=True)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='trang/')),
            ],
        ),
    ]
