# Generated by Django 5.2.7 on 2025-11-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangleepage', '0005_trangnoidung'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('noi_dung', models.TextField()),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
