# Generated by Django 5.2.7 on 2025-11-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangleepage', '0006_cauhoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoiDap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_hoi', models.CharField(max_length=255)),
                ('cau_tra_loi', models.TextField()),
                ('hien_thi', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CauHoi',
        ),
    ]
